name: check-metadata

on:
  pull_request:
    branches:
      - main
    paths:
      - 'games/**.js'

permissions:
  contents: read
  pull-requests: read

jobs:
  check-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.1
        with:
          files: |
            games/**.js

      - name: Check game metadata
        run: |
          failed=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking $file..."
            
            # Check for required metadata fields
            missing=""
            
            if ! grep -q '@title:' "$file"; then
              missing="$missing @title"
            fi
            
            if ! grep -q '@author:' "$file"; then
              missing="$missing @author"
            fi
            
            if ! grep -q '@tags:' "$file"; then
              missing="$missing @tags"
            fi
            
            if ! grep -q '@addedOn:' "$file"; then
              missing="$missing @addedOn"
            fi
            
            if ! grep -q '@description:' "$file"; then
              missing="$missing @description"
            fi
            
            if [ -n "$missing" ]; then
              echo "::error file=$file::Missing required metadata:$missing"
              failed=1
            else
              echo "✓ $file has all required metadata"
            fi
          done
          
          if [ $failed -eq 1 ]; then
            echo ""
            echo "Required metadata format (in a comment block at top of file):"
            echo "/*"
            echo "@title: Your Game Title"
            echo "@author: Your Name"
            echo "@tags: ['puzzle', 'action']"
            echo "@addedOn: 2024-01-15"
            echo "@description: A short description of your game"
            echo "*/"
            exit 1
          fi
